<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="NRedisStack" />
    <PackageReference Include="RazorLight" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMP.DataAccess\DMP.DataAccess.csproj" />
  </ItemGroup>

</Project>
